### ISSUE TITLE
Twitter: tweet deletion after send fail

### ISSUE THREAD

**Issue by ylorant** [ylorant/HedgeBot#12]
When a tweet fails sending the bot still acknowledges the tweet as sent and deletes it. This should not happen. Maybe create a "failed sending" status ?

**Comment by RomainOdeval** [comment]
I don't remember exactly how its saved into Hedgebot but maybe a new data on each tweet like "status" with value like "created", "send", "send_failed" and "send_successed" ?

**Comment by ylorant** [comment]
Right now we're just setting a "sent" property to true or false, or directly deleting the tweet after the send if the plugin has been configured to do so.

Having multiple statuses would be a better idea indeed, and allow for more flexible situation handling, such as when sending fails. Definitely a good idea.

**Comment by ylorant** [comment]
Multiple statuses have been implemented.
